// src/components/common/Header.tsx
import styled                   from 'styled-components';
import { theme }                from 'assets/style/theme';
import Logo                     from 'components/common/Logo';

const HeaderComponent = styled.header`
    padding:8px;
    position:sticky;
    top:0;
    z-index:9;

    .box {
        position:relative;
        border-radius:32px;
        height:60px;
        background:rgba(${theme.color['tertiary-rgb']},.96);
        backdrop-filter:blur(6px);
    }

    .logo {
        position:absolute;
        top:50%; left:50%;
        transform:translate(-50%, -50%);
    }
    .github {
        position:absolute;
        top:50%; right:8px;
        transform:translate(-50%, -50%);
    }
`

function Content() {
    return (
        <HeaderComponent>
            <div className="box">
                <Logo className="logo" color="#fff"/>
                <svg className="github" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path id="social-github" d="M14.25,2.25a12.158,12.158,0,0,0-12,12.306,12.281,12.281,0,0,0,8.207,11.673.941.941,0,0,0,.2.021.581.581,0,0,0,.616-.611c0-.295-.011-1.066-.016-2.094a5.486,5.486,0,0,1-1.211.145,2.789,2.789,0,0,1-2.834-1.794,3.252,3.252,0,0,0-1.334-1.8c-1.045-.734-.005-.755.075-.755h.005A2.581,2.581,0,0,1,7.8,20.614a2.356,2.356,0,0,0,2.121,1.345,3.375,3.375,0,0,0,1.371-.322,2.66,2.66,0,0,1,.76-1.645c-2.663-.311-5.464-1.366-5.464-6.08a4.817,4.817,0,0,1,1.232-3.3,4.528,4.528,0,0,1,.118-3.257,1,1,0,0,1,.268-.027A5.7,5.7,0,0,1,11.239,8.62a11.154,11.154,0,0,1,6.011,0,5.7,5.7,0,0,1,3.032-1.291,1,1,0,0,1,.268.027,4.533,4.533,0,0,1,.118,3.257,4.837,4.837,0,0,1,1.232,3.3c0,4.725-2.807,5.765-5.48,6.069a2.982,2.982,0,0,1,.814,2.277c0,1.645-.016,2.973-.016,3.375a.578.578,0,0,0,.611.616,1.037,1.037,0,0,0,.214-.021A12.281,12.281,0,0,0,26.25,14.556,12.158,12.158,0,0,0,14.25,2.25Z" transform="translate(-2.25 -2.25)" fill="#f7f7f7"/>
                </svg>
            </div>
        </HeaderComponent>
    );
}

export default Content;

// src/common/Header.svelte
<script lang="ts">
    import Logo from '@src/common/Log.svelte';
    import IconWrap from '@src/common/IconWrap.svelte';

    import profileImg from '@src/img/profile.png';
    import { onMount } from 'svelte';

    let header:HTMLElement;

    const dom = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path id="패스_3" data-name="패스 3" d="M0,0V24H24V0ZM14.534,19.59c-.406.078-.534-.171-.534-.384V17.011a1.906,1.906,0,0,0-.55-1.481c1.782-.2,3.654-.875,3.654-3.947a3.086,3.086,0,0,0-.824-2.147A2.87,2.87,0,0,0,16.2,7.319s-.671-.215-2.2.82a7.565,7.565,0,0,0-4.006,0c-1.528-1.035-2.2-.82-2.2-.82A2.879,2.879,0,0,0,7.72,9.435,3.092,3.092,0,0,0,6.9,11.582c0,3.064,1.867,3.751,3.645,3.954a1.7,1.7,0,0,0-.508,1.07A1.7,1.7,0,0,1,7.7,15.94a1.683,1.683,0,0,0-1.227-.825s-.78-.01-.055.487a2.118,2.118,0,0,1,.889,1.17S7.775,18.2,10,17.716V19.2c0,.211-.129.459-.528.385a8,8,0,1,1,5.062,0Z" fill="#333"/></svg>`;

    onMount(() => {
        
        const headerFloat = function(e) {
            const scroll = document.documentElement.scrollTop;
            const offset = this.offsetTop;
            if(scroll >= offset){
                this.classList.remove('header-on-float');
            }else{
                this.classList.add('header-on-float');
            }
        }.bind(header);

        // let scrollOffset = header.offsetTop;
        window.addEventListener('scroll', headerFloat);
    });


</script>

<header bind:this={header} class="header-on-float wrap">
    <div class="header-background">
        <div class="header-background-2 flex-box flex-middle">
            <div class="flex-box flex-middle flex-left">
                <Logo/>
            </div>
            <div class="flex-box flex-middle flex-right flex-fill">
                <IconWrap src={profileImg} alt="프로필 이미지" w={24} h={24} style="margin-right:16px;"/>
                <IconWrap svg={dom} alt="깃허브 이미지" w={24} h={24}/>
            </div>
        </div>
    </div>
</header>

<style>
    header {
        position:sticky;
        top:0;
        width:100%;
        height:60px;
        transition:all 0.5s;
        transition-timing-function:linear;
    }
    header.header-on-float {
        padding:10px;
        height:80px;
    }
    header:not(.header-on-float){
        max-width:100vw;
    }
    header:not(.header-on-float) .header-background-2 {
        max-width:1080px;
        height:100%;
        background:none;
        box-shadow:none;
        padding:0;
    }

    header .header-background {
        background:rgba(242,242,242,0.8);
        backdrop-filter:blur(5px);
        padding:2px;
        width:100%;
        height:100%;
        box-shadow:0 8px 16px rgba(0,0,0,0.1);
    }
    header.header-on-float .header-background {
        border-radius:14px;
    }

    header .header-background-2 {
        width:100%;
        height:100%;
        background:rgba(255,255,255,0.5);
        box-shadow:0 1px 2px rgba(0,0,0,0.1);
        padding:0 16px;

        margin:0 auto;
        max-width:100vw;

        transition:all 0.5s;
        transition-timing-function:linear;
    }
    header.header-on-float .header-background-2 {
        border-radius:12px;
    }
</style>
